theme: jekyll-theme-primer

title: Décrire et manipuler un document numérique
description: Contenus pour le cours « Décrire et manipuler un document numérique  », L2 SDL parcours LCN, université Paris Nanterre
emojicon: 📑

url: https://loicgrobol.github.io/
baseurl: "/document-numerique"
repository: "loicgrobol/document-numerique"

exclude:
  - renv

include:
  - _pages