---
title: "Décrire et manipuler un document numérique"
subtitle: "Exercices XML"
author: L. Grobol
lang: "fr"
output:
  pdf_document:
    latex_engine: "lualatex"
---

## 1. Documents bien formés

Tiré de <https://pageperso.lis-lab.fr/~pierre-alain.reynier/XML/tp1/tp1.html>

Pour chacun des quatre fichiers XML suivants, dire s'il est bien formé et s'il ne l'est pas, dire
pourquoi et proposer une correction.

- Ce sont des fichiers textes tout à fait normaux, qui s'ouvrent dans n'importe quel éditeur de
  texte (voir les cours précédents)

Fichiers :

- [exemple 1](samples/simple1.xml)
- [exemple 2](samples/simple2.xml)
- [exemple 3](samples/simple3.xml)
- [exemple 4](samples/simple4.xml)


# 2. Modélisation

Créer des documents XML qui permettront de structurer les (toutes petites) bases de données
suivantes. Essayer de leur donner une structure aussi simple, régulière et lisible que possible.

## 1. Bibliographie

On veut pouvoir représenter les informations suivantes : titre, année de publication, genre et auteurice(s).

- Frankenstein; or, The Modern Prometheus (1918) – roman fantastique – Mary Shelley
- Les Méprisés, grand roman de mœurs parisiennes (1882) – roman – Louise Michel et Jean Guêtré
- Aṣṭādhyāyī (-400) – grammaire - Pāṇini

## 2. Fruits

Les informations à représenter sont : produit, origine, quantité (comprenant valeur et unité) et prix.

- Bananes (Antilles françaises) – 500g – 1.69€
- Mandarines (Espagne) – 750g – 3.49€
- Kiwis (Italie) – 1kg – 2.49€

## 3. Carnet d’adresses

Les informations à représenter sont : nom, profession et coordonnées (comprenant adresse, email et numéro de téléphone).

- Soazig Bras – Médecin – 5 rue du Grand Docteur - `soaz@tuta.com` – 03 98 44 89 30
- Anne le Brun – Propriétaire – 18 avenue de la Résidence - `arctos@you.me` – 05 55 66 55 50
- Kevin Dillot – Coursier – 6 rue de la Course – `serieuxetresponsable@codeberg.page` 07 32 23 70 22
