---
title: "Décrire et manipuler un document numérique"
subtitle: "Introduction"
author:
  - "L. Grobol `<lgrobol@parisnanterre.fr>`"
institute: Université Paris Nanterre
format:
  pdf:
    "pdf-engine": "lualatex"
  revealjs:
    css: "../reveal_slides_style.css"
    theme: white
    highlight: pygments
    center: true
    reveal_options:
      slideNumber: true
      progress: true
    self-contained: true
lang: "fr"
---

# Bonjour

- Loïc Grobol (il/iel) [<lgrobol@parisnanterre.fr>](mailto:lgrobol@parisnanterre.fr)
- PHILLIA / MoDyCo (Bâtiment Rémond, 4ème, bureau 404C)
- *Office hours*, etc.: voir <https://lgrobol.bzh/teaching>
- **N'hésitez pas à m'écrire**

# Le cours

## Infos pratiques

- **Quoi** « Décrire et manipuler un document numérique » 4L4SC02P
- **Où** Salle M209, bâtiment Éphémère 1, Université Paris Nanterre, 200 avenue de la République,
  Nanterre
- **Quand** 12 séances, les lundis de 13:20 à 15:20, du 20/01 au 14/04
  - Voir le calendrier de l'université pour les dates de vacances.

→ Travail sur machine préférable, amener si possible un PC portable

## Liens

- La page du cours (slides, documents, nouvelles, consignes…)
  - → <https://loicgrobol.github.io/document-numerique>
- Le dépôt GitHub (code source, compléments et historique)
  - → <https://github.com/LoicGrobol/document-numerique>

## Objectifs

Connaissances :

- Savoir ce qu'est un document numérique.
- Savoir comment différents types de documents sont représentés dans des systèmes informatiques.
- Connaissances précises sur les représentations numériques des documents textuels.
- Connaissances de bases sur ce que sont Internet et le Web et leurs fonctionnements.

---

Compétences :

- Créer et modifier des pages web simples avec HTML et CSS.
- Créer et modifier des documents XML simples.
- Créer et modifier des documents structurés en Markdown.
- Utiliser des expressions régulières pour faire des recherches et des modifications dans des
  fichiers textes.

## Évaluation

- Exercices en temps libre pendant le semestre
- Examen final

# Documents numérique

- Qu'est-ce qu'un document ?

## En *Humanités Numériques*

> Un document est une **trace** permettant d’**interpréter** un **événement passé** à partir d’un
> **contrat de lecture**. (Jean-Michel Salün (2012), « Vu, lu, su. Les architectes de l'information
> face au monopole du web »)

. . .

À partir de ces éléments, qu'est-ce qui caractérise un document numérique ?

## Documents et supports numériques

:::incremental

- Ce qui différencie un document numérique, c'est d'abord le type de **trace** concerné.
- Ce qui a évidemment des conséquences sur ce qu'on peut représenter.
- Dans ce cours, c'est donc sur cette *trace*, ce *support* qu'on va se concentrer.

:::

---

La question principale pour nous sera en général : « Étant donné un document, comment le représenter
sous forme numérique ?
