on: [push, pull_request]

name: CI-CD

jobs:
  CI-CD:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }}

    strategy:
      # we keep a matrix for convenience, but we would always want to run on one
      # single OS and R version
      matrix:
        config:
          - os: ubuntu-20.04

    env:
      JEKYLL_DEBUG: "true"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            ggplot2
            rcmdcheck
          needs: |
            revealjs
            rmarkdown

      - uses: r-lib/actions/setup-tinytex@v2
        env:
          TINYTEX_INSTALLER: TinyTeX-1

      - name: Build site
        run: |
          for (slide_file in Sys.glob("slides/*/*-slides.md")){
            rmarkdown::render(slide_file, output_format='all')
          }
        shell: Rscript {0}

      - name: 💎 setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true

      - name: 🔨 install dependencies & build site
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true
          custom_opts: '--verbose'
      
      - name: Prevent Github Jekyll build
        run: |
          touch _site/.nojekyll

      - name: Deploy to GitHub Pages 🚀
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@4.1.8
        with:
          branch: gh-pages
          folder: _site
          single-commit: true

